AWSTemplateFormatVersion: '2010-09-09'
Description: The AWS CloudFormation template for this Serverless application's resources
  outside of Lambdas and Api Gateway
Resources:
  IamRoleLambda:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: [lambda.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
  IamPolicyLambda:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ${stage}-${project}-lambda
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
            - es:*
          Resource:
            - '*'
        - Effect: Allow
          Action:
           - s3:GetObject
          Resource: 'arn:aws:s3:::test-tax-bucket/*'
        - Effect: Allow
          Action:
           - s3:ListBucket
          Resource: 'arn:aws:s3:::test-tax-bucket'
        - Effect: Allow
          Action: ['logs:CreateLogGroup', 'logs:CreateLogStream', 'logs:PutLogEvents']
          Resource: arn:aws:logs:${region}:*:*
      Roles:
      - {Ref: IamRoleLambda}
Outputs:
  IamRoleArnLambda:
    Description: ARN of the lambda IAM role
    Value:
      Fn::GetAtt: [IamRoleLambda, Arn]
